filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /suricata-logs/eve.json
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["host.docker.internal:5044"]
