input {
  file {
    path => "/var/log/suricata/eve.json"
    codec => "json"
    type => "SuricataIDPS"
    start_position => "beginning"
  }
}

filter {
  if [event_type] == "alert" {
    mutate {
      rename => { "[alert][signature]" => "rule_name" }
      rename => { "[alert][signature_id]" => "rule_sid" }
      rename => { "[alert][severity]" => "severity" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "project3-suricata-%{+YYYY.MM.dd}"
  }
}
